version: '3.8'
networks:
  line_app:
services:
  app:
    container_name: line_bot
    build: .
    ports:
      - "9000:9000"
    volumes: 
      - ./credentials:/opt/app/credentials
      - ./media:/temp/
    networks:
      - line_app
  ngrok:
    container_name: ngrok
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: app:9000
      NGROK_REGION: us
      NGROK_AUTH: ${NGROK_AUTH_TOKEN}
    depends_on:
      - app
    networks:
      - line_app

# linux/amd64, linux/arm and linux/arm64 のプラットフォームの場合は、以下を使用してください。
  # ngrok:
  #   container_name: ngrok
  #   image: athombv/ngrok:latest
  #   command: >
  #           ngrok http
  #           --region=ap
  #           --authtoken=$NGROK_AUTH_TOKEN
  #           app:9000
  #   depends_on:
  #     - app
  #   networks:
  #     - line_app