client_config_file: credentials/client_secret.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive